import Head from "next/head";
import dotenv from 'dotenv';
import { useSelector } from "react-redux";
import { RootState } from "@/redux/store";



dotenv.config();
export default function Home() {

  const { data } = useSelector((state: RootState) => state.api);
  console.log("first", data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`d-flex container-fluid p-4 gap-3 `}
      >
        <div className="d-flex  justify-content-center align-items-center    container-fluid" >
          <h1 className="">This is Overview Page</h1>
        </div>
      </div>
    </>
  );
}
